print('Hello World, I have been at UofT for 4 years including PEY')
print('Hello World Justin')
print('Hello Justin, this is your teammate Omar!')
print('Hey Justin, Toby is invading your repo')
print('c3')
print('c4')
